create type public.app_role as enum ('admin', 'staff');
create type public.record_status as enum ('Active', 'Trial', 'Inactive');
create type public.coach_type as enum ('Head', 'Assistant');
create type public.payment_status as enum ('Paid', 'Partial', 'Unpaid');
create type public.payment_method as enum ('Cash', 'Bank Transfer', 'Touch ''n Go eWallet', 'Online', 'Others');
create type public.payout_type as enum ('Head', 'Assistant');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  role public.app_role not null default 'staff',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.branches (
  id bigint generated by default as identity primary key,
  name text not null,
  subtitle text not null default '',
  status text not null default 'Active' check (status in ('Active', 'Inactive')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.branch_memberships (
  user_id uuid not null references public.profiles(id) on delete cascade,
  branch_id bigint not null references public.branches(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, branch_id)
);

create table public.academy_settings (
  singleton boolean primary key default true check (singleton),
  academy_name text not null default 'Titan Storm Basketball Academy',
  logo_path text,
  default_branch_id bigint references public.branches(id) on delete set null,
  updated_at timestamptz not null default now()
);

create table public.students (
  id bigint generated by default as identity primary key,
  branch_id bigint not null references public.branches(id) on delete restrict,
  name text not null,
  nric text not null default '',
  gender text not null default '' check (gender in ('', 'Male', 'Female')),
  date_of_birth date,
  height text not null default '',
  school text not null default '',
  tshirt_size text not null default '',
  student_phone text not null default '',
  parent_name text not null default '',
  parent_contact text not null default '',
  email text not null default '',
  father_height text not null default '',
  mother_height text not null default '',
  monthly_fee numeric(12,2) check (monthly_fee is null or monthly_fee >= 0),
  level text not null default '' check (level in ('', 'Beginner', 'Intermediate', 'Advanced')),
  status public.record_status not null default 'Active',
  photo_path text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.coaches (
  id bigint generated by default as identity primary key,
  branch_id bigint not null references public.branches(id) on delete restrict,
  name text not null,
  phone text not null default '',
  coach_type public.coach_type not null default 'Head',
  hourly_rate numeric(12,2) not null default 0 check (hourly_rate >= 0),
  status text not null default 'Active' check (status in ('Active', 'Inactive')),
  photo_path text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.classes (
  id bigint generated by default as identity primary key,
  branch_id bigint not null references public.branches(id) on delete cascade,
  label text not null,
  day_of_week text not null check (day_of_week in ('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday')),
  start_time time,
  end_time time,
  coach_id bigint references public.coaches(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (start_time is null or end_time is null or end_time > start_time)
);

create table public.sessions (
  id bigint generated by default as identity primary key,
  branch_id bigint not null references public.branches(id) on delete cascade,
  class_id bigint not null references public.classes(id) on delete cascade,
  session_date date not null,
  notes text not null default '',
  coach_id bigint references public.coaches(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (class_id, session_date)
);

create table public.enrollments (
  id bigint generated by default as identity primary key,
  branch_id bigint not null references public.branches(id) on delete cascade,
  student_id bigint not null references public.students(id) on delete cascade,
  class_id bigint not null references public.classes(id) on delete cascade,
  start_date date not null default current_date,
  created_at timestamptz not null default now(),
  unique (student_id, class_id)
);

create table public.attendance (
  student_id bigint not null references public.students(id) on delete cascade,
  session_id bigint not null references public.sessions(id) on delete cascade,
  class_id bigint not null references public.classes(id) on delete cascade,
  branch_id bigint not null references public.branches(id) on delete cascade,
  attendance_date date not null,
  status text not null default '' check (status in ('', 'Present')),
  remarks text not null default '',
  recorded_by uuid references public.profiles(id) on delete set null default auth.uid(),
  recorded_at timestamptz not null default now(),
  primary key (student_id, session_id)
);

create table public.coach_payments (
  id bigint generated by default as identity primary key,
  branch_id bigint not null references public.branches(id) on delete restrict,
  coach_id bigint not null references public.coaches(id) on delete restrict,
  payout_type public.payout_type not null,
  pay_month date,
  amount numeric(12,2) not null check (amount >= 0),
  units numeric(12,2) not null default 0,
  rate numeric(12,2) not null default 0,
  students_count integer not null default 0,
  date_paid date not null default current_date,
  remarks text not null default '',
  recorded_by uuid references public.profiles(id) on delete set null default auth.uid(),
  recorded_at timestamptz not null default now()
);

create table public.payments (
  id bigint generated by default as identity primary key,
  branch_id bigint not null references public.branches(id) on delete restrict,
  student_id bigint not null references public.students(id) on delete cascade,
  fee_month date not null check (fee_month = date_trunc('month', fee_month)::date),
  amount numeric(12,2) not null default 0 check (amount >= 0),
  method public.payment_method,
  status public.payment_status not null default 'Paid',
  date_received date,
  remarks text not null default '',
  reference_no text not null default '',
  coach_id bigint references public.coaches(id) on delete restrict,
  commission_settled boolean not null default false,
  coach_payment_id bigint references public.coach_payments(id) on delete set null,
  receipt_path text,
  recorded_by uuid references public.profiles(id) on delete set null default auth.uid(),
  recorded_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.head_coach_rates (
  id bigint generated by default as identity primary key,
  min_students integer not null check (min_students >= 0),
  max_students integer not null check (max_students >= min_students),
  min_fee numeric(12,2) not null check (min_fee >= 0),
  max_fee numeric(12,2) not null check (max_fee >= min_fee),
  payout numeric(12,2) not null check (payout >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.coach_payment_lines (
  id bigint generated by default as identity primary key,
  coach_payment_id bigint not null references public.coach_payments(id) on delete cascade,
  payment_id bigint not null references public.payments(id) on delete restrict,
  student_id bigint not null references public.students(id) on delete restrict,
  student_fee numeric(12,2),
  students_count integer not null,
  payout numeric(12,2) not null default 0,
  matched boolean not null default false,
  unique (coach_payment_id, payment_id)
);

create table public.coach_attendance (
  id bigint generated by default as identity primary key,
  branch_id bigint not null references public.branches(id) on delete cascade,
  session_id bigint not null references public.sessions(id) on delete cascade,
  class_id bigint not null references public.classes(id) on delete cascade,
  attendance_date date not null,
  coach_id bigint not null references public.coaches(id) on delete restrict,
  hours numeric(8,2) not null check (hours >= 0),
  recorded_by uuid references public.profiles(id) on delete set null default auth.uid(),
  recorded_at timestamptz not null default now(),
  unique (session_id, coach_id)
);

create index students_branch_idx on public.students(branch_id, status, name);
create index coaches_branch_idx on public.coaches(branch_id, status, name);
create index classes_branch_idx on public.classes(branch_id, day_of_week);
create index sessions_branch_date_idx on public.sessions(branch_id, session_date);
create index enrollments_branch_student_idx on public.enrollments(branch_id, student_id);
create index attendance_branch_date_idx on public.attendance(branch_id, attendance_date);
create index payments_branch_month_idx on public.payments(branch_id, fee_month);
create index payments_coach_unsettled_idx on public.payments(branch_id, coach_id, commission_settled) where status = 'Paid';
create index coach_payments_branch_coach_idx on public.coach_payments(branch_id, coach_id, date_paid desc);
create index coach_attendance_branch_date_idx on public.coach_attendance(branch_id, attendance_date);
create unique index payments_reference_unique_idx on public.payments(branch_id, lower(reference_no)) where btrim(reference_no) <> '';

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger profiles_touch before update on public.profiles for each row execute function public.touch_updated_at();
create trigger branches_touch before update on public.branches for each row execute function public.touch_updated_at();
create trigger students_touch before update on public.students for each row execute function public.touch_updated_at();
create trigger coaches_touch before update on public.coaches for each row execute function public.touch_updated_at();
create trigger classes_touch before update on public.classes for each row execute function public.touch_updated_at();
create trigger sessions_touch before update on public.sessions for each row execute function public.touch_updated_at();
create trigger payments_touch before update on public.payments for each row execute function public.touch_updated_at();
create trigger rates_touch before update on public.head_coach_rates for each row execute function public.touch_updated_at();
create trigger settings_touch before update on public.academy_settings for each row execute function public.touch_updated_at();

create or replace function public.protect_last_active_branch()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if tg_op = 'DELETE' then
    if old.status = 'Active' and not exists(select 1 from public.branches where id <> old.id and status = 'Active') then
      raise exception 'Cannot deactivate or delete the only active branch';
    end if;
    return old;
  end if;
  if old.status = 'Active' and new.status = 'Inactive'
    and not exists(select 1 from public.branches where id <> old.id and status = 'Active') then
    raise exception 'Cannot deactivate or delete the only active branch';
  end if;
  return new;
end;
$$;

create trigger branches_protect_last before update or delete on public.branches for each row execute function public.protect_last_active_branch();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', split_part(coalesce(new.email, ''), '@', 1)),
    case when exists(select 1 from public.profiles) then 'staff'::public.app_role else 'admin'::public.app_role end
  );
  return new;
end;
$$;

create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(select 1 from public.profiles where id = auth.uid() and role = 'admin');
$$;

create or replace function public.can_access_branch(p_branch_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.is_admin() or exists(
    select 1 from public.branch_memberships
    where user_id = auth.uid() and branch_id = p_branch_id
  );
$$;

create or replace function public.sync_class_branch()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  v_coach_branch bigint;
begin
  if new.coach_id is not null then
    select branch_id into v_coach_branch from public.coaches where id = new.coach_id;
    if v_coach_branch is distinct from new.branch_id then raise exception 'Coach must belong to the same branch'; end if;
  end if;
  return new;
end;
$$;

create or replace function public.sync_session_branch()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  v_branch bigint;
  v_coach_branch bigint;
begin
  select branch_id into strict v_branch from public.classes where id = new.class_id;
  new.branch_id = v_branch;
  if new.coach_id is not null then
    select branch_id into v_coach_branch from public.coaches where id = new.coach_id;
    if v_coach_branch is distinct from v_branch then raise exception 'Coach must belong to the same branch'; end if;
  end if;
  return new;
end;
$$;

create or replace function public.sync_enrollment_branch()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  v_student_branch bigint;
  v_class_branch bigint;
begin
  select branch_id into strict v_student_branch from public.students where id = new.student_id;
  select branch_id into strict v_class_branch from public.classes where id = new.class_id;
  if v_student_branch is distinct from v_class_branch then raise exception 'Student and class must belong to the same branch'; end if;
  new.branch_id = v_student_branch;
  return new;
end;
$$;

create or replace function public.sync_attendance_fields()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  v_student_branch bigint;
  v_session_branch bigint;
  v_class_id bigint;
  v_date date;
begin
  select branch_id into strict v_student_branch from public.students where id = new.student_id;
  select branch_id, class_id, session_date into strict v_session_branch, v_class_id, v_date from public.sessions where id = new.session_id;
  if v_student_branch is distinct from v_session_branch then raise exception 'Student and session must belong to the same branch'; end if;
  new.branch_id = v_session_branch;
  new.class_id = v_class_id;
  new.attendance_date = v_date;
  new.recorded_by = auth.uid();
  new.recorded_at = now();
  return new;
end;
$$;

create or replace function public.sync_payment_fields()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  v_student_branch bigint;
  v_coach_branch bigint;
begin
  select branch_id into strict v_student_branch from public.students where id = new.student_id;
  new.branch_id = v_student_branch;
  if new.coach_id is not null then
    select branch_id into v_coach_branch from public.coaches where id = new.coach_id;
    if v_coach_branch is distinct from v_student_branch then raise exception 'Coach must belong to the same branch'; end if;
  end if;
  return new;
end;
$$;

create or replace function public.sync_coach_payment_fields()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  v_branch bigint;
  v_type public.coach_type;
begin
  select branch_id, coach_type into strict v_branch, v_type from public.coaches where id = new.coach_id;
  new.branch_id = v_branch;
  new.payout_type = v_type::text::public.payout_type;
  return new;
end;
$$;

create or replace function public.sync_coach_attendance_fields()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  v_session_branch bigint;
  v_class bigint;
  v_date date;
  v_coach_branch bigint;
  v_start time;
  v_end time;
begin
  select branch_id, class_id, session_date into strict v_session_branch, v_class, v_date from public.sessions where id = new.session_id;
  select branch_id into strict v_coach_branch from public.coaches where id = new.coach_id;
  if v_session_branch is distinct from v_coach_branch then raise exception 'Coach and session must belong to the same branch'; end if;
  new.branch_id = v_session_branch;
  new.class_id = v_class;
  new.attendance_date = v_date;
  if tg_op = 'INSERT' or not public.is_admin() then
    select start_time, end_time into v_start, v_end from public.classes where id = v_class;
    new.hours = case when v_start is null or v_end is null then 0 else round((extract(epoch from (v_end - v_start)) / 3600)::numeric, 2) end;
  end if;
  return new;
end;
$$;

create trigger classes_sync before insert or update on public.classes for each row execute function public.sync_class_branch();
create trigger sessions_sync before insert or update on public.sessions for each row execute function public.sync_session_branch();
create trigger enrollments_sync before insert or update on public.enrollments for each row execute function public.sync_enrollment_branch();
create trigger attendance_sync before insert or update on public.attendance for each row execute function public.sync_attendance_fields();
create trigger payments_sync before insert or update on public.payments for each row execute function public.sync_payment_fields();
create trigger coach_payments_sync before insert or update on public.coach_payments for each row execute function public.sync_coach_payment_fields();
create trigger coach_attendance_sync before insert or update on public.coach_attendance for each row execute function public.sync_coach_attendance_fields();

create or replace function public.generate_sessions(p_class_id bigint, p_start_date date, p_end_date date)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_class public.classes%rowtype;
  v_date date;
  v_created integer := 0;
  v_target integer;
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;
  if p_end_date < p_start_date then raise exception 'End date must be after start date'; end if;
  select * into strict v_class from public.classes where id = p_class_id;
  if not public.can_access_branch(v_class.branch_id) then raise exception 'Branch access denied'; end if;
  v_target = array_position(array['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'], v_class.day_of_week) - 1;
  v_date = p_start_date;
  while extract(dow from v_date)::integer <> v_target and v_date <= p_end_date loop
    v_date = v_date + 1;
  end loop;
  while v_date <= p_end_date loop
    insert into public.sessions (branch_id, class_id, session_date, coach_id)
    values (v_class.branch_id, v_class.id, v_date, v_class.coach_id)
    on conflict (class_id, session_date) do nothing;
    if found then v_created = v_created + 1; end if;
    v_date = v_date + 7;
  end loop;
  return v_created;
end;
$$;

create or replace function public.record_student_payment(
  p_student_id bigint,
  p_fee_months date[],
  p_amount numeric,
  p_method public.payment_method,
  p_status public.payment_status,
  p_date_received date,
  p_remarks text default '',
  p_reference_no text default '',
  p_coach_id bigint default null,
  p_receipt_path text default null
)
returns bigint[]
language plpgsql
security definer
set search_path = public
as $$
declare
  v_branch bigint;
  v_primary date;
  v_month date;
  v_id bigint;
  v_ids bigint[] := '{}';
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;
  if coalesce(array_length(p_fee_months, 1), 0) = 0 then raise exception 'At least one fee month is required'; end if;
  select branch_id into strict v_branch from public.students where id = p_student_id;
  if not public.can_access_branch(v_branch) then raise exception 'Branch access denied'; end if;
  select max(date_trunc('month', month_value)::date) into v_primary from unnest(p_fee_months) as months(month_value);
  foreach v_month in array p_fee_months loop
    v_month = date_trunc('month', v_month)::date;
    insert into public.payments (
      branch_id, student_id, fee_month, amount, method, status, date_received,
      remarks, reference_no, coach_id, receipt_path
    ) values (
      v_branch,
      p_student_id,
      v_month,
      case when v_month = v_primary then p_amount else 0 end,
      p_method,
      p_status,
      p_date_received,
      case when v_month = v_primary then coalesce(p_remarks, '') else 'Paid in ' || to_char(v_primary, 'FMMonth YYYY') end,
      case when v_month = v_primary then coalesce(p_reference_no, '') else '' end,
      p_coach_id,
      p_receipt_path
    ) returning id into v_id;
    v_ids = array_append(v_ids, v_id);
  end loop;
  return v_ids;
end;
$$;

create or replace function public.replace_head_coach_rates(p_rates jsonb)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;
  delete from public.head_coach_rates;
  insert into public.head_coach_rates (min_students, max_students, min_fee, max_fee, payout)
  select min_students, max_students, min_fee, max_fee, payout
  from jsonb_to_recordset(coalesce(p_rates, '[]'::jsonb)) as rate_rows(
    min_students integer,
    max_students integer,
    min_fee numeric,
    max_fee numeric,
    payout numeric
  );
end;
$$;

create or replace function public.get_head_coach_commission(p_coach_id bigint, p_branch_id bigint)
returns jsonb
language plpgsql
security definer
stable
set search_path = public
as $$
declare
  v_students integer;
  v_result jsonb;
begin
  if not public.can_access_branch(p_branch_id) then raise exception 'Branch access denied'; end if;
  if not exists(select 1 from public.coaches where id = p_coach_id and branch_id = p_branch_id and coach_type = 'Head') then raise exception 'Head coach not found'; end if;
  select count(distinct student_id) into v_students
  from public.payments
  where branch_id = p_branch_id and coach_id = p_coach_id and status = 'Paid' and not commission_settled;
  with units as (
    select p.id, p.student_id, s.name as student_name, p.fee_month, p.date_received, s.monthly_fee,
      coalesce((select r.payout from public.head_coach_rates r
        where v_students between r.min_students and r.max_students
          and s.monthly_fee between r.min_fee and r.max_fee
        order by r.min_students desc, r.min_fee desc limit 1), 0) as payout
    from public.payments p
    join public.students s on s.id = p.student_id
    where p.branch_id = p_branch_id and p.coach_id = p_coach_id and p.status = 'Paid' and not p.commission_settled
  )
  select jsonb_build_object(
    'type', 'Head',
    'units', count(*),
    'students', v_students,
    'commission', coalesce(sum(payout), 0),
    'unmatched', count(*) filter (where monthly_fee is null or payout = 0),
    'items', coalesce(jsonb_agg(jsonb_build_object(
      'paymentId', id,
      'studentId', student_id,
      'studentName', student_name,
      'feeMonth', to_char(fee_month, 'YYYY-MM'),
      'dateReceived', date_received,
      'receivedMonth', to_char(date_received, 'YYYY-MM'),
      'fee', monthly_fee,
      'payout', payout
    ) order by date_received desc nulls last, student_name, fee_month), '[]'::jsonb)
  ) into v_result from units;
  return v_result;
end;
$$;

create or replace function public.get_assistant_pay(p_coach_id bigint, p_branch_id bigint, p_month date)
returns jsonb
language plpgsql
security definer
stable
set search_path = public
as $$
declare
  v_rate numeric;
  v_result jsonb;
begin
  if not public.can_access_branch(p_branch_id) then raise exception 'Branch access denied'; end if;
  select hourly_rate into strict v_rate from public.coaches
  where id = p_coach_id and branch_id = p_branch_id and coach_type = 'Assistant';
  with entries as (
    select ca.attendance_date, c.label as class_name, ca.hours
    from public.coach_attendance ca
    join public.classes c on c.id = ca.class_id
    where ca.coach_id = p_coach_id and ca.branch_id = p_branch_id
      and ca.attendance_date >= date_trunc('month', p_month)::date
      and ca.attendance_date < (date_trunc('month', p_month) + interval '1 month')::date
  )
  select jsonb_build_object(
    'type', 'Assistant',
    'month', to_char(p_month, 'YYYY-MM'),
    'hours', coalesce(sum(hours), 0),
    'hourlyRate', v_rate,
    'total', coalesce(sum(hours), 0) * v_rate,
    'sessions', coalesce(jsonb_agg(jsonb_build_object('date', attendance_date, 'className', class_name, 'hours', hours) order by attendance_date desc), '[]'::jsonb)
  ) into v_result from entries;
  return v_result;
end;
$$;

create or replace function public.record_coach_payout(
  p_coach_id bigint,
  p_amount numeric,
  p_units numeric,
  p_rate numeric,
  p_students_count integer,
  p_date_paid date,
  p_remarks text default '',
  p_pay_month date default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_coach public.coaches%rowtype;
  v_payout_id bigint;
  v_payment_ids bigint[] := '{}'::bigint[];
  v_students_count integer := p_students_count;
  v_units numeric := p_units;
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;
  select * into strict v_coach from public.coaches where id = p_coach_id for update;
  if not public.can_access_branch(v_coach.branch_id) then raise exception 'Branch access denied'; end if;
  if v_coach.coach_type = 'Head' then
    select coalesce(array_agg(id), '{}'::bigint[]), count(distinct student_id)
    into v_payment_ids, v_students_count
    from (
      select p.id, p.student_id
      from public.payments p
      where p.branch_id = v_coach.branch_id and p.coach_id = v_coach.id and p.status = 'Paid' and not p.commission_settled
      for update
    ) locked_payments;
    v_units = cardinality(v_payment_ids);
  end if;
  insert into public.coach_payments (branch_id, coach_id, payout_type, pay_month, amount, units, rate, students_count, date_paid, remarks)
  values (v_coach.branch_id, v_coach.id, v_coach.coach_type::text::public.payout_type, p_pay_month, p_amount, v_units, p_rate, v_students_count, p_date_paid, coalesce(p_remarks, ''))
  returning id into v_payout_id;
  if v_coach.coach_type = 'Head' then
    with lines as (
      select p.id, p.student_id, s.monthly_fee,
        coalesce((select r.payout from public.head_coach_rates r
          where v_students_count between r.min_students and r.max_students
            and s.monthly_fee between r.min_fee and r.max_fee
          order by r.min_students desc, r.min_fee desc limit 1), 0) as line_payout
      from public.payments p
      join public.students s on s.id = p.student_id
      where p.id = any(v_payment_ids)
    )
    insert into public.coach_payment_lines (coach_payment_id, payment_id, student_id, student_fee, students_count, payout, matched)
    select v_payout_id, id, student_id, monthly_fee, v_students_count, line_payout, monthly_fee is not null and line_payout > 0
    from lines;
    update public.payments p
    set commission_settled = true, coach_payment_id = v_payout_id, updated_at = now()
    where p.id = any(v_payment_ids);
  end if;
  return v_payout_id;
end;
$$;

create or replace function public.undo_coach_payout(p_coach_payment_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_branch bigint;
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;
  select branch_id into strict v_branch from public.coach_payments where id = p_coach_payment_id for update;
  if not public.can_access_branch(v_branch) then raise exception 'Branch access denied'; end if;
  update public.payments set commission_settled = false, coach_payment_id = null, updated_at = now()
  where coach_payment_id = p_coach_payment_id;
  delete from public.coach_payments where id = p_coach_payment_id;
end;
$$;

alter table public.profiles enable row level security;
alter table public.branches enable row level security;
alter table public.branch_memberships enable row level security;
alter table public.academy_settings enable row level security;
alter table public.students enable row level security;
alter table public.coaches enable row level security;
alter table public.classes enable row level security;
alter table public.sessions enable row level security;
alter table public.enrollments enable row level security;
alter table public.attendance enable row level security;
alter table public.payments enable row level security;
alter table public.head_coach_rates enable row level security;
alter table public.coach_payments enable row level security;
alter table public.coach_payment_lines enable row level security;
alter table public.coach_attendance enable row level security;

create policy profiles_read_self on public.profiles for select to authenticated using (id = auth.uid() or public.is_admin());
create policy profiles_admin_update on public.profiles for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy branches_read on public.branches for select to authenticated using (public.can_access_branch(id));
create policy branches_admin_all on public.branches for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy memberships_read on public.branch_memberships for select to authenticated using (user_id = auth.uid() or public.is_admin());
create policy memberships_admin_all on public.branch_memberships for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy settings_read on public.academy_settings for select to authenticated using (true);
create policy settings_admin_all on public.academy_settings for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy students_read on public.students for select to authenticated using (public.can_access_branch(branch_id));
create policy students_admin_all on public.students for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy students_staff_trial_insert on public.students for insert to authenticated with check (public.can_access_branch(branch_id) and status = 'Trial');
create policy coaches_read on public.coaches for select to authenticated using (public.can_access_branch(branch_id));
create policy coaches_admin_all on public.coaches for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy classes_read on public.classes for select to authenticated using (public.can_access_branch(branch_id));
create policy classes_admin_all on public.classes for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy sessions_read on public.sessions for select to authenticated using (public.can_access_branch(branch_id));
create policy sessions_admin_all on public.sessions for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy sessions_staff_insert on public.sessions for insert to authenticated with check (public.can_access_branch(branch_id) and session_date = current_date);
create policy enrollments_read on public.enrollments for select to authenticated using (public.can_access_branch(branch_id));
create policy enrollments_admin_all on public.enrollments for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy attendance_read on public.attendance for select to authenticated using (public.can_access_branch(branch_id));
create policy attendance_write on public.attendance for all to authenticated using (public.can_access_branch(branch_id)) with check (public.can_access_branch(branch_id));
create policy coach_attendance_read on public.coach_attendance for select to authenticated using (public.can_access_branch(branch_id));
create policy coach_attendance_write on public.coach_attendance for all to authenticated using (public.can_access_branch(branch_id)) with check (public.can_access_branch(branch_id));

create policy payments_admin_all on public.payments for all to authenticated using (public.is_admin() and public.can_access_branch(branch_id)) with check (public.is_admin() and public.can_access_branch(branch_id));
create policy rates_admin_all on public.head_coach_rates for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy coach_payments_admin_all on public.coach_payments for all to authenticated using (public.is_admin() and public.can_access_branch(branch_id)) with check (public.is_admin() and public.can_access_branch(branch_id));
create policy coach_payment_lines_admin_read on public.coach_payment_lines for select to authenticated using (public.is_admin() and exists(select 1 from public.coach_payments cp where cp.id = coach_payment_id and public.can_access_branch(cp.branch_id)));

insert into public.branches (name, subtitle) values ('Main Branch', 'Bukit Jalil');
insert into public.academy_settings (academy_name, default_branch_id) values ('Titan Storm Basketball Academy', 1);
insert into public.head_coach_rates (min_students, max_students, min_fee, max_fee, payout) values
  (1, 49, 0, 99, 20),
  (1, 49, 100, 149, 30),
  (1, 49, 150, 99999, 50);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types) values
  ('student-photos', 'student-photos', true, 5242880, array['image/jpeg','image/png','image/webp']),
  ('coach-photos', 'coach-photos', true, 5242880, array['image/jpeg','image/png','image/webp']),
  ('academy-assets', 'academy-assets', true, 5242880, array['image/jpeg','image/png','image/webp','image/svg+xml']),
  ('payment-receipts', 'payment-receipts', false, 10485760, array['image/jpeg','image/png','image/webp','application/pdf'])
on conflict (id) do nothing;

create policy public_images_read on storage.objects for select using (bucket_id in ('student-photos', 'coach-photos', 'academy-assets'));
create policy admin_storage_insert on storage.objects for insert to authenticated with check (public.is_admin() and bucket_id in ('student-photos', 'coach-photos', 'academy-assets', 'payment-receipts'));
create policy admin_storage_update on storage.objects for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy admin_storage_delete on storage.objects for delete to authenticated using (public.is_admin());
create policy receipt_admin_read on storage.objects for select to authenticated using (bucket_id = 'payment-receipts' and public.is_admin());

grant execute on function public.generate_sessions(bigint, date, date) to authenticated;
grant execute on function public.record_student_payment(bigint, date[], numeric, public.payment_method, public.payment_status, date, text, text, bigint, text) to authenticated;
grant execute on function public.replace_head_coach_rates(jsonb) to authenticated;
grant execute on function public.get_head_coach_commission(bigint, bigint) to authenticated;
grant execute on function public.get_assistant_pay(bigint, bigint, date) to authenticated;
grant execute on function public.record_coach_payout(bigint, numeric, numeric, numeric, integer, date, text, date) to authenticated;
grant execute on function public.undo_coach_payout(bigint) to authenticated;
